# Site settings
title: Frontend VO Blog
email: ar@manoderecha.mx
description: > # this means to ignore newlines until "baseurl:"
  We're a bunch of guys working at vincoorbis doing front-end stuff
baseurl: "/frontendvo-blog" # the subpath of your site, e.g. /blog/
url: "https://vinco.github.io" # the base hostname & protocol for your site
twitter_username: vincoorbis
github_username:  vinco

# Files handled by gulp
exclude: [
  'gulpfile.coffee',
  'node_modules',
  'package.json',
  'bower.json',
  'images',
  'fonts',
  '**.png',
  '**.jpg',
  '**.jpeg',
  '**.gif',
  '**.webp',
  '**.svg'
]

include:
  - .no-jekyll

# Build settings
source: .staging
destination: dist
future: true
show_drafts: true

# Permalinks
permalink: "/:short_year/:month/:title"

# Plugins
markdown: redcarpet

redcarpet:
  extensions: ['tables',
   'autolink',
   'strikethrough',
   'space_after_headers',
   'with_toc_data',
   'fenced_code_blocks'
  ]
